name       : xdg-desktop-portal-gtk
version    : 0.5
release    : 2
source     :
    - https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/0.5/xdg-desktop-portal-gtk-0.5.tar.xz : 790744654f361203c5578fd04d7576b1c5fa2cad9cdd2f595672dd07415c4591
license    : LGPL-2.1
component  : desktop.util
summary    : GTK+ backend for XDG Portal
description: |
    A backend implementation for xdg-desktop-portal that is using GTK+ and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces.
builddeps  :
    - pkgconfig(xdg-desktop-portal)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - xdg-desktop-portal
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
