name       : xdg-desktop-portal-gtk
version    : 1.8.0
release    : 8
source     :
    - https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.8.0/xdg-desktop-portal-gtk-1.8.0.tar.xz : a52529ed321e044ca9adca5e9718d9ba57c414a2634dd4109df344c5b9eed77f
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : GTK+ backend for XDG Portal
description: |
    A backend implementation for xdg-desktop-portal that is using GTK+ and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(flatpak)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(xdg-desktop-portal)
rundeps    :
    - xdg-desktop-portal
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
