name       : xdg-desktop-portal-gtk
version    : 1.0.2
release    : 6
source     :
    - https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.0.2/xdg-desktop-portal-gtk-1.0.2.tar.xz : 4ce552d36b165fc619ed33084d7044d230ff633aa5e54f1fd23ca9afb0cefc93
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : GTK+ backend for XDG Portal
description: |
    A backend implementation for xdg-desktop-portal that is using GTK+ and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(flatpak)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xdg-desktop-portal)
rundeps    :
    - xdg-desktop-portal
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
