name       : xdg-desktop-portal-gtk
version    : '1.0'
release    : 4
source     :
    - https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.0/xdg-desktop-portal-gtk-1.0.tar.xz : 6c9d246cbfa2a1ccea773cb6ed565644e4ee64b1655707850da8d53ffcecee24
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : GTK+ backend for XDG Portal
description: |
    A backend implementation for xdg-desktop-portal that is using GTK+ and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(flatpak)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xdg-desktop-portal)
rundeps    :
    - xdg-desktop-portal
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
