name       : xdg-desktop-portal-gtk
version    : 0.11
release    : 3
source     :
    - https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/0.11/xdg-desktop-portal-gtk-0.11.tar.xz : 3c4f3891c16f63e1ef327bacc55b1aba5a49c2855e4b63d10d8d0accacfba429
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : GTK+ backend for XDG Portal
description: |
    A backend implementation for xdg-desktop-portal that is using GTK+ and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xdg-desktop-portal)
rundeps    :
    - xdg-desktop-portal
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
