name       : xdg-desktop-portal-gtk
version    : 1.14.1
release    : 16
source     :
    - https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.14.1/xdg-desktop-portal-gtk-1.14.1.tar.xz : 3ee2a992187eabb237a76170a7dead2a3bcea2edbf59344647cc0d1c640a5700
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : GTK+ backend for XDG Portal
description: |
    A backend implementation for xdg-desktop-portal that is using GTK+ and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(flatpak)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(xdg-desktop-portal)
rundeps    :
    - xdg-desktop-portal
setup      : |
    %configure \
        --enable-appchooser \
        --enable-background \
        --enable-screencast \
        --enable-screenshot \
        --enable-settings \
        --enable-wallpaper
build      : |
    %make
install    : |
    %make_install
