name       : xdg-desktop-portal-gtk
version    : 1.14.0
release    : 12
source     :
    - https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.14.0/xdg-desktop-portal-gtk-1.14.0.tar.xz : f621210716a9cf821d969eecb1df1e3e46fc687b87f7add83300d35321594954
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : GTK+ backend for XDG Portal
description: |
    A backend implementation for xdg-desktop-portal that is using GTK+ and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(flatpak)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(xdg-desktop-portal)
rundeps    :
    - xdg-desktop-portal
setup      : |
    %configure \
        --enable-appchooser \
        --enable-background \
        --enable-screencast \
        --enable-screenshot \
        --enable-settings \
        --enable-wallpaper
build      : |
    %make
install    : |
    %make_install
