name       : xdg-desktop-portal-gtk
version    : 1.10.0
release    : 10
source     :
    - https://github.com/flatpak/xdg-desktop-portal-gtk/releases/download/1.10.0/xdg-desktop-portal-gtk-1.10.0.tar.xz : c809757bb5cb5d067a99be373b36a05578e0f710c1d69aad7222e98d4db38b5a
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : GTK+ backend for XDG Portal
description: |
    A backend implementation for xdg-desktop-portal that is using GTK+ and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(flatpak)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(xdg-desktop-portal)
rundeps    :
    - xdg-desktop-portal
setup      : |
    %configure \
        --enable-appchooser \
        --enable-background \
        --enable-screencast \
        --enable-screenshot \
        --enable-settings \
        --enable-wallpaper
build      : |
    %make
install    : |
    %make_install
